AWSTemplateFormatVersion: '2010-09-09'
Description: This template deploys a Fargate ECS task to use the ECS cluster deployed
Resources:
  
  

# These are the values output by the CloudFormation template. Be careful
# about changing any of them, because of them are exported with specific
# names so that the other task related CF templates can use them.
Outputs:
  FargateTaskChimeBroadcast:
    Description: The ID of the Fargate Task created
    Value: !Ref 'FargateTaskChimeBroadcast'
    Export:
      Name: !Join [ ':', [ !Ref 'AWS::StackName', 'FargateTaskChimeBroadcast' ] ]
  